version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
  esphome:
    container_name: esphome
    image: esphome/esphome:2022.11
    volumes:
      - ./esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.15
    volumes:
      - ./mosquitto/config:/mosquitto/config/
      - ./mosquitto/log:/mosquitto/log/
      - ./mosquitto/data:/mosquitto/data/
    restart: always
    # privileged: true
    # network_mode: host
    ports:
      - 1883:1883
      - 9001:9001

volumes:
  data: ~
