substitutions:
  disp_name: esp321
  update_time: 10s
  v_gain: "7773"
  i_gain_50A1V_sct013: "38504"
  i_gain_100A50mA_sct013: "29055"

esphome:
  name: emon-esp32-1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp_api_key

ota:
  password: !secret esp_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_pass

spi:
  clk_pin: 18
  miso_pin: 19
  mosi_pin: 23

# Enable time component to reset energy at midnight
time:
  - platform: sntp
    id: my_time

sensor:
  - platform: wifi_signal
    name: ${disp_name} WiFi
    update_interval: 60s
  # Board 1, Left Side
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      voltage:
        name: ${disp_name} B1L Volts
        id: b1lVolts
      current:
        name: ${disp_name} B1L CT1 Amps
        id: b1lct1Amps
      gain_voltage: ${v_gain}
      gain_ct: ${i_gain_50A1V_sct013}
    phase_b:
      current:
        name: ${disp_name} B1L CT2 Amps
        id: b1lct2Amps
      gain_ct: ${i_gain_50A1V_sct013}
    phase_c:
      current:
        name: ${disp_name} B1L CT3 Amps
        id: b1lct3Amps
      gain_ct: ${i_gain_50A1V_sct013}
    frequency:
      name: ${disp_name} Freq B1L
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B1L CT1 Watts
    id: b1lct1Watts
    lambda: return id(b1lct1Amps).state * id(b1lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B1L CT2 Watts
    id: b1lct2Watts
    lambda: return id(b1lct2Amps).state * id(b1lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B1L CT3 Watts
    id: b1lct3Watts
    lambda: return id(b1lct3Amps).state * id(b1lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: total_daily_energy
    name: DiningRm_B1_1L_50A.wh
    power_id: b1lct1Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: Stove_B1_2L_50A.wh
    power_id: b1lct2Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: SEKitchen_B1_3L_50A.wh
    power_id: b1lct3Watts
    unit_of_measurement: Wh
  # Board 1, Right Side
  - platform: atm90e32
    cs_pin: 4
    phase_a:
      voltage:
        name: ${disp_name} B1R Volts
        id: b1rVolts
      current:
        name: ${disp_name} B1R CT1 Amps
        id: b1rct1Amps
      gain_voltage: ${v_gain}
      gain_ct: ${i_gain_50A1V_sct013}
    phase_b:
      current:
        name: ${disp_name} B1R CT2 Amps
        id: b1rct2Amps
      gain_ct: ${i_gain_50A1V_sct013}
    phase_c:
      current:
        name: ${disp_name} B1R CT3 Amps
        id: b1rct3Amps
      gain_ct: ${i_gain_50A1V_sct013}
    frequency:
      name: ${disp_name} Freq B1R
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B1R CT1 Watts
    id: b1rct1Watts
    lambda: return id(b1rct1Amps).state * id(b1rVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B1R CT2 Watts
    id: b1rct2Watts
    lambda: return id(b1rct2Amps).state * id(b1rVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B1R CT3 Watts
    id: b1rct3Watts
    lambda: return id(b1rct3Amps).state * id(b1rVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: total_daily_energy
    name: SadieRm_B1_1R_50A.wh
    power_id: b1rct1Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: GarbageDisposal_B1_2R_50A.wh
    power_id: b1rct2Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: UpstairsEBr_B1_3R_50A.wh
    power_id: b1rct3Watts
    unit_of_measurement: Wh
  # Board 2, Left Side
  - platform: atm90e32
    cs_pin: 0
    phase_a:
      voltage:
        name: ${disp_name} B2L Volts
        id: b2lVolts
      current:
        name: ${disp_name} B2L CT1 Amps
        id: b2lct1Amps
      gain_voltage: ${v_gain}
      gain_ct: ${i_gain_50A1V_sct013}
    phase_b:
      current:
        name: ${disp_name} B2L CT2 Amps
        id: b2lct2Amps
      gain_ct: ${i_gain_50A1V_sct013}
    phase_c:
      current:
        name: ${disp_name} B2L CT3 Amps
        id: b2lct3Amps
      gain_ct: ${i_gain_50A1V_sct013}
    frequency:
      name: ${disp_name} Freq B2L
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B2L CT1 Watts
    id: b2lct1Watts
    lambda: return id(b2lct1Amps).state * id(b2lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B2L CT2 Watts
    id: b2lct2Watts
    lambda: return id(b2lct2Amps).state * id(b2lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B2L CT3 Watts
    id: b2lct3Watts
    lambda: return id(b2lct3Amps).state * id(b2lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: total_daily_energy
    name: Sunroom_B2_1L_50A.wh
    power_id: b2lct1Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: BasementLts_B2_2L_50A.wh
    power_id: b2lct2Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: Unknown_B2_3L_50A.wh
    power_id: b2lct3Watts
    unit_of_measurement: Wh
  # Board 2, Right Side
  - platform: atm90e32
    cs_pin: 16
    phase_a:
      voltage:
        name: ${disp_name} B2R Volts
        id: b2rVolts
      current:
        name: ${disp_name} B2R CT1 Amps
        id: b2rct1Amps
      gain_voltage: ${v_gain}
      gain_ct: ${i_gain_50A1V_sct013}
    phase_b:
      current:
        name: ${disp_name} B2R CT2 Amps
        id: b2rct2Amps
      gain_ct: ${i_gain_50A1V_sct013}
    phase_c:
      current:
        name: ${disp_name} B2R CT3 Amps
        id: b2rct3Amps
      gain_ct: ${i_gain_50A1V_sct013}
    frequency:
      name: ${disp_name} Freq B2R
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B2R CT1 Watts
    id: b2rct1Watts
    lambda: return id(b2rct1Amps).state * id(b2rVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B2R CT2 Watts
    id: b2rct2Watts
    lambda: return id(b2rct2Amps).state * id(b2rVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B2R CT3 Watts
    id: b2rct3Watts
    lambda: return id(b2rct3Amps).state * id(b2rVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: total_daily_energy
    name: LivingRm_B2_1R_50A.wh
    power_id: b2rct1Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: Fridge_B2_2R_50A.wh
    power_id: b2rct2Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: LaundryRm_B2_3R_50A.wh
    power_id: b2rct3Watts
    unit_of_measurement: Wh

  # Board 3, Left Side
  - platform: atm90e32
    cs_pin: 15
    phase_a:
      voltage:
        name: ${disp_name} B3L Volts
        id: b3lVolts
      current:
        name: ${disp_name} B3L CT1 Amps
        id: b3lct1Amps
      gain_voltage: ${v_gain}
      gain_ct: ${i_gain_100A50mA_sct013}
    phase_b:
      current:
        name: ${disp_name} B3L CT2 Amps
        id: b3lct2Amps
      gain_ct: ${i_gain_100A50mA_sct013}
    phase_c:
      current:
        name: ${disp_name} B3L CT3 Amps
        id: b3lct3Amps
      gain_ct: ${i_gain_100A50mA_sct013}
    frequency:
      name: ${disp_name} Freq B3L
    line_frequency: 60Hz
    gain_pga: 1X
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B3L CT1 Watts
    id: b3lct1Watts
    lambda: return id(b3lct1Amps).state * id(b3lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B3L CT2 Watts
    id: b3lct2Watts
    lambda: return id(b3lct2Amps).state * id(b3lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: template
    name: ${disp_name} B3L CT3 Watts
    id: b3lct3Watts
    lambda: return id(b3lct3Amps).state * id(b3lVolts).state;
    accuracy_decimals: 2
    unit_of_measurement: W
    update_interval: ${update_time}
  - platform: total_daily_energy
    name: WaterHtr_B3_1L_100A.wh
    power_id: b3lct1Watts
    unit_of_measurement: Wh
  - platform: total_daily_energy
    name: WaterHtr_B3_2L_100A.wh
    power_id: b3lct2Watts
    unit_of_measurement: Wh
